local mct_mod = mct:register_mod("jadawin_unnatural_selection_2")

mct_mod:set_title ("Unnatural Selection 2", false)
mct_mod:set_author ("Jadawin")
mct_mod:set_description ("Strengthen or Weaken Selected AI Factions", false)

local option_wh_main_brt_artois = mct_mod:add_new_option ("wh_main_brt_artois", "slider")
option_wh_main_brt_artois:set_text("BRT Artois")
option_wh_main_brt_artois:set_tooltip_text("Buff/Debuff for BRT Artois")
option_wh_main_brt_artois:slider_set_min_max(-3, 3)
option_wh_main_brt_artois:slider_set_step_size(1)
option_wh_main_brt_artois:set_default_value(0)

local option_wh_main_brt_bastonne = mct_mod:add_new_option ("wh_main_brt_bastonne", "slider")
option_wh_main_brt_bastonne:set_text("BRT Bastonne")
option_wh_main_brt_bastonne:set_tooltip_text("Buff/Debuff for BRT Bastonne")
option_wh_main_brt_bastonne:slider_set_min_max(-3, 3)
option_wh_main_brt_bastonne:slider_set_step_size(1)
option_wh_main_brt_bastonne:set_default_value(0)

local option_wh_main_brt_bordeleaux = mct_mod:add_new_option ("wh_main_brt_bordeleaux", "slider")
option_wh_main_brt_bordeleaux:set_text("BRT Bordeleaux")
option_wh_main_brt_bordeleaux:set_tooltip_text("Buff/Debuff for BRT Bordeleaux")
option_wh_main_brt_bordeleaux:slider_set_min_max(-3, 3)
option_wh_main_brt_bordeleaux:slider_set_step_size(1)
option_wh_main_brt_bordeleaux:set_default_value(0)

local option_wh_main_brt_carcassonne = mct_mod:add_new_option ("wh_main_brt_carcassonne", "slider")
option_wh_main_brt_carcassonne:set_text("BRT Carcassonne")
option_wh_main_brt_carcassonne:set_tooltip_text("Buff/Debuff for BRT Carcassonne")
option_wh_main_brt_carcassonne:slider_set_min_max(-3, 3)
option_wh_main_brt_carcassonne:slider_set_step_size(1)
option_wh_main_brt_carcassonne:set_default_value(0)

local option_wh2_dlc14_brt_chevaliers_de_lyonesse = mct_mod:add_new_option ("wh2_dlc14_brt_chevaliers_de_lyonesse", "slider")
option_wh2_dlc14_brt_chevaliers_de_lyonesse:set_text("BRT Chevaliers de Lyonesse")
option_wh2_dlc14_brt_chevaliers_de_lyonesse:set_tooltip_text("Buff/Debuff for BRT Chevaliers de Lyonesse")
option_wh2_dlc14_brt_chevaliers_de_lyonesse:slider_set_min_max(-3, 3)
option_wh2_dlc14_brt_chevaliers_de_lyonesse:slider_set_step_size(1)
option_wh2_dlc14_brt_chevaliers_de_lyonesse:set_default_value(0)

local option_wh_main_brt_bretonnia = mct_mod:add_new_option ("wh_main_brt_bretonnia", "slider")
option_wh_main_brt_bretonnia:set_text("BRT Couronne")
option_wh_main_brt_bretonnia:set_tooltip_text("Buff/Debuff for BRT Couronne")
option_wh_main_brt_bretonnia:slider_set_min_max(-3, 3)
option_wh_main_brt_bretonnia:slider_set_step_size(1)
option_wh_main_brt_bretonnia:set_default_value(0)

local option_wh2_main_brt_knights_of_origo = mct_mod:add_new_option ("wh2_main_brt_knights_of_origo", "slider")
option_wh2_main_brt_knights_of_origo:set_text("BRT Knights of Origo")
option_wh2_main_brt_knights_of_origo:set_tooltip_text("Buff/Debuff for BRT Knights of Origo")
option_wh2_main_brt_knights_of_origo:slider_set_min_max(-3, 3)
option_wh2_main_brt_knights_of_origo:slider_set_step_size(1)
option_wh2_main_brt_knights_of_origo:set_default_value(0)

local option_wh2_main_brt_knights_of_the_flame = mct_mod:add_new_option ("wh2_main_brt_knights_of_the_flame", "slider")
option_wh2_main_brt_knights_of_the_flame:set_text("BRT Knights of the Flame")
option_wh2_main_brt_knights_of_the_flame:set_tooltip_text("Buff/Debuff for BRT Knights of the Flame")
option_wh2_main_brt_knights_of_the_flame:slider_set_min_max(-3, 3)
option_wh2_main_brt_knights_of_the_flame:slider_set_step_size(1)
option_wh2_main_brt_knights_of_the_flame:set_default_value(0)

local option_wh_main_brt_lyonesse = mct_mod:add_new_option ("wh_main_brt_lyonesse", "slider")
option_wh_main_brt_lyonesse:set_text("BRT Lyonesse")
option_wh_main_brt_lyonesse:set_tooltip_text("Buff/Debuff for BRT Lyonesse")
option_wh_main_brt_lyonesse:slider_set_min_max(-3, 3)
option_wh_main_brt_lyonesse:slider_set_step_size(1)
option_wh_main_brt_lyonesse:set_default_value(0)

local option_wh_main_brt_parravon = mct_mod:add_new_option ("wh_main_brt_parravon", "slider")
option_wh_main_brt_parravon:set_text("BRT Parravon")
option_wh_main_brt_parravon:set_tooltip_text("Buff/Debuff for BRT Parravon")
option_wh_main_brt_parravon:slider_set_min_max(-3, 3)
option_wh_main_brt_parravon:slider_set_step_size(1)
option_wh_main_brt_parravon:set_default_value(0)

local option_wh2_main_brt_thegans_crusaders = mct_mod:add_new_option ("wh2_main_brt_thegans_crusaders", "slider")
option_wh2_main_brt_thegans_crusaders:set_text("BRT Thegan's Errantry")
option_wh2_main_brt_thegans_crusaders:set_tooltip_text("Buff/Debuff for BRT Thegan's Errantry")
option_wh2_main_brt_thegans_crusaders:slider_set_min_max(-3, 3)
option_wh2_main_brt_thegans_crusaders:slider_set_step_size(1)
option_wh2_main_brt_thegans_crusaders:set_default_value(0)

local option_wh_dlc03_bst_beastmen = mct_mod:add_new_option ("wh_dlc03_bst_beastmen", "slider")
option_wh_dlc03_bst_beastmen:set_text("BST Beastmen")
option_wh_dlc03_bst_beastmen:set_tooltip_text("Buff/Debuff for BST Beastmen")
option_wh_dlc03_bst_beastmen:slider_set_min_max(-3, 3)
option_wh_dlc03_bst_beastmen:slider_set_step_size(1)
option_wh_dlc03_bst_beastmen:set_default_value(0)

local option_wh2_main_bst_blooded_axe = mct_mod:add_new_option ("wh2_main_bst_blooded_axe", "slider")
option_wh2_main_bst_blooded_axe:set_text("BST Blooded-Axe Tribe")
option_wh2_main_bst_blooded_axe:set_tooltip_text("Buff/Debuff for BST Blooded-Axe Tribe")
option_wh2_main_bst_blooded_axe:slider_set_min_max(-3, 3)
option_wh2_main_bst_blooded_axe:slider_set_step_size(1)
option_wh2_main_bst_blooded_axe:set_default_value(0)

local option_wh_dlc03_bst_jagged_horn = mct_mod:add_new_option ("wh_dlc03_bst_jagged_horn", "slider")
option_wh_dlc03_bst_jagged_horn:set_text("BST Jagged-Horn Tribe")
option_wh_dlc03_bst_jagged_horn:set_tooltip_text("Buff/Debuff for BST Jagged-Horn Tribe")
option_wh_dlc03_bst_jagged_horn:slider_set_min_max(-3, 3)
option_wh_dlc03_bst_jagged_horn:slider_set_step_size(1)
option_wh_dlc03_bst_jagged_horn:set_default_value(0)

local option_wh2_main_bst_manblight = mct_mod:add_new_option ("wh2_main_bst_manblight", "slider")
option_wh2_main_bst_manblight:set_text("BST Manblight Tribe")
option_wh2_main_bst_manblight:set_tooltip_text("Buff/Debuff for BST Manblight Tribe")
option_wh2_main_bst_manblight:slider_set_min_max(-3, 3)
option_wh2_main_bst_manblight:slider_set_step_size(1)
option_wh2_main_bst_manblight:set_default_value(0)

local option_wh_dlc03_bst_redhorn = mct_mod:add_new_option ("wh_dlc03_bst_redhorn", "slider")
option_wh_dlc03_bst_redhorn:set_text("BST Redhorn Tribe")
option_wh_dlc03_bst_redhorn:set_tooltip_text("Buff/Debuff for BST Redhorn Tribe")
option_wh_dlc03_bst_redhorn:slider_set_min_max(-3, 3)
option_wh_dlc03_bst_redhorn:slider_set_step_size(1)
option_wh_dlc03_bst_redhorn:set_default_value(0)

local option_wh2_main_bst_ripper_horn = mct_mod:add_new_option ("wh2_main_bst_ripper_horn", "slider")
option_wh2_main_bst_ripper_horn:set_text("BST Ripper-Horn Tribe")
option_wh2_main_bst_ripper_horn:set_tooltip_text("Buff/Debuff for BST Ripper-Horn Tribe")
option_wh2_main_bst_ripper_horn:slider_set_min_max(-3, 3)
option_wh2_main_bst_ripper_horn:slider_set_step_size(1)
option_wh2_main_bst_ripper_horn:set_default_value(0)

local option_wh2_main_bst_shadowgor = mct_mod:add_new_option ("wh2_main_bst_shadowgor", "slider")
option_wh2_main_bst_shadowgor:set_text("BST Shadowgor Warherd")
option_wh2_main_bst_shadowgor:set_tooltip_text("Buff/Debuff for BST Shadowgor Warherd")
option_wh2_main_bst_shadowgor:slider_set_min_max(-3, 3)
option_wh2_main_bst_shadowgor:slider_set_step_size(1)
option_wh2_main_bst_shadowgor:set_default_value(0)

local option_wh2_main_bst_stone_horn = mct_mod:add_new_option ("wh2_main_bst_stone_horn", "slider")
option_wh2_main_bst_stone_horn:set_text("BST Stone-Horn Tribe")
option_wh2_main_bst_stone_horn:set_tooltip_text("Buff/Debuff for BST Stone-Horn Tribe")
option_wh2_main_bst_stone_horn:slider_set_min_max(-3, 3)
option_wh2_main_bst_stone_horn:slider_set_step_size(1)
option_wh2_main_bst_stone_horn:set_default_value(0)

local option_wh_dlc03_bst_beastmen_chaos = mct_mod:add_new_option ("wh_dlc03_bst_beastmen_chaos", "slider")
option_wh_dlc03_bst_beastmen_chaos:set_text("BST Warherd of Chaos")
option_wh_dlc03_bst_beastmen_chaos:set_tooltip_text("Buff/Debuff for BST Warherd of Chaos")
option_wh_dlc03_bst_beastmen_chaos:slider_set_min_max(-3, 3)
option_wh_dlc03_bst_beastmen_chaos:slider_set_step_size(1)
option_wh_dlc03_bst_beastmen_chaos:set_default_value(0)

local option_wh2_main_chs_chaos_incursion_skv = mct_mod:add_new_option ("wh2_main_chs_chaos_incursion_skv", "slider")
option_wh2_main_chs_chaos_incursion_skv:set_text("CHS Followers of Chaos")
option_wh2_main_chs_chaos_incursion_skv:set_tooltip_text("Buff/Debuff for CHS Followers of Chaos")
option_wh2_main_chs_chaos_incursion_skv:slider_set_min_max(-3, 3)
option_wh2_main_chs_chaos_incursion_skv:slider_set_step_size(1)
option_wh2_main_chs_chaos_incursion_skv:set_default_value(0)

local option_wh2_main_chs_chaos_incursion_hef = mct_mod:add_new_option ("wh2_main_chs_chaos_incursion_hef", "slider")
option_wh2_main_chs_chaos_incursion_hef:set_text("CHS Puppets of Chaos")
option_wh2_main_chs_chaos_incursion_hef:set_tooltip_text("Buff/Debuff for CHS Puppets of Chaos")
option_wh2_main_chs_chaos_incursion_hef:slider_set_min_max(-3, 3)
option_wh2_main_chs_chaos_incursion_hef:slider_set_step_size(1)
option_wh2_main_chs_chaos_incursion_hef:set_default_value(0)

local option_wh2_main_chs_chaos_incursion_def = mct_mod:add_new_option ("wh2_main_chs_chaos_incursion_def", "slider")
option_wh2_main_chs_chaos_incursion_def:set_text("CHS Servants to Chaos")
option_wh2_main_chs_chaos_incursion_def:set_tooltip_text("Buff/Debuff for CHS Servants to Chaos")
option_wh2_main_chs_chaos_incursion_def:slider_set_min_max(-3, 3)
option_wh2_main_chs_chaos_incursion_def:slider_set_step_size(1)
option_wh2_main_chs_chaos_incursion_def:set_default_value(0)

local option_wh2_main_chs_chaos_incursion_lzd = mct_mod:add_new_option ("wh2_main_chs_chaos_incursion_lzd", "slider")
option_wh2_main_chs_chaos_incursion_lzd:set_text("CHS Vessels of Chaos")
option_wh2_main_chs_chaos_incursion_lzd:set_tooltip_text("Buff/Debuff for CHS Vessels of Chaos")
option_wh2_main_chs_chaos_incursion_lzd:slider_set_min_max(-3, 3)
option_wh2_main_chs_chaos_incursion_lzd:slider_set_step_size(1)
option_wh2_main_chs_chaos_incursion_lzd:set_default_value(0)

local option_wh_main_chs_chaos = mct_mod:add_new_option ("wh_main_chs_chaos", "slider")
option_wh_main_chs_chaos:set_text("CHS Warriors of Chaos")
option_wh_main_chs_chaos:set_tooltip_text("Buff/Debuff for CHS Warriors of Chaos")
option_wh_main_chs_chaos:slider_set_min_max(-3, 3)
option_wh_main_chs_chaos:slider_set_step_size(1)
option_wh_main_chs_chaos:set_default_value(0)

local option_wh2_dlc11_cst_pirates_of_sartosa = mct_mod:add_new_option ("wh2_dlc11_cst_pirates_of_sartosa", "slider")
option_wh2_dlc11_cst_pirates_of_sartosa:set_text("CST Pirates of Sartosa")
option_wh2_dlc11_cst_pirates_of_sartosa:set_tooltip_text("Buff/Debuff for CST Pirates of Sartosa")
option_wh2_dlc11_cst_pirates_of_sartosa:slider_set_min_max(-3, 3)
option_wh2_dlc11_cst_pirates_of_sartosa:slider_set_step_size(1)
option_wh2_dlc11_cst_pirates_of_sartosa:set_default_value(0)

local option_wh2_dlc11_cst_vampire_coast = mct_mod:add_new_option ("wh2_dlc11_cst_vampire_coast", "slider")
option_wh2_dlc11_cst_vampire_coast:set_text("CST The Awakened")
option_wh2_dlc11_cst_vampire_coast:set_tooltip_text("Buff/Debuff for CST The Awakened")
option_wh2_dlc11_cst_vampire_coast:slider_set_min_max(-3, 3)
option_wh2_dlc11_cst_vampire_coast:slider_set_step_size(1)
option_wh2_dlc11_cst_vampire_coast:set_default_value(0)

local option_wh2_dlc11_cst_noctilus = mct_mod:add_new_option ("wh2_dlc11_cst_noctilus", "slider")
option_wh2_dlc11_cst_noctilus:set_text("CST The Dreadfleet")
option_wh2_dlc11_cst_noctilus:set_tooltip_text("Buff/Debuff for CST The Dreadfleet")
option_wh2_dlc11_cst_noctilus:slider_set_min_max(-3, 3)
option_wh2_dlc11_cst_noctilus:slider_set_step_size(1)
option_wh2_dlc11_cst_noctilus:set_default_value(0)

local option_wh2_dlc11_cst_the_drowned = mct_mod:add_new_option ("wh2_dlc11_cst_the_drowned", "slider")
option_wh2_dlc11_cst_the_drowned:set_text("CST The Drowned")
option_wh2_dlc11_cst_the_drowned:set_tooltip_text("Buff/Debuff for CST The Drowned")
option_wh2_dlc11_cst_the_drowned:slider_set_min_max(-3, 3)
option_wh2_dlc11_cst_the_drowned:slider_set_step_size(1)
option_wh2_dlc11_cst_the_drowned:set_default_value(0)

local option_wh2_main_def_bleak_holds = mct_mod:add_new_option ("wh2_main_def_bleak_holds", "slider")
option_wh2_main_def_bleak_holds:set_text("DEF Bleak Holds")
option_wh2_main_def_bleak_holds:set_tooltip_text("Buff/Debuff for DEF Bleak Holds")
option_wh2_main_def_bleak_holds:slider_set_min_max(-3, 3)
option_wh2_main_def_bleak_holds:slider_set_step_size(1)
option_wh2_main_def_bleak_holds:set_default_value(0)

local option_wh2_main_def_blood_hall_coven = mct_mod:add_new_option ("wh2_main_def_blood_hall_coven", "slider")
option_wh2_main_def_blood_hall_coven:set_text("DEF Blood Hall Coven")
option_wh2_main_def_blood_hall_coven:set_tooltip_text("Buff/Debuff for DEF Blood Hall Coven")
option_wh2_main_def_blood_hall_coven:slider_set_min_max(-3, 3)
option_wh2_main_def_blood_hall_coven:slider_set_step_size(1)
option_wh2_main_def_blood_hall_coven:set_default_value(0)

local option_wh2_dlc10_def_blood_voyage = mct_mod:add_new_option ("wh2_dlc10_def_blood_voyage", "slider")
option_wh2_dlc10_def_blood_voyage:set_text("DEF Blood Voyage")
option_wh2_dlc10_def_blood_voyage:set_tooltip_text("Buff/Debuff for DEF Blood Voyage")
option_wh2_dlc10_def_blood_voyage:slider_set_min_max(-3, 3)
option_wh2_dlc10_def_blood_voyage:slider_set_step_size(1)
option_wh2_dlc10_def_blood_voyage:set_default_value(0)

local option_wh2_main_def_clar_karond = mct_mod:add_new_option ("wh2_main_def_clar_karond", "slider")
option_wh2_main_def_clar_karond:set_text("DEF Clar Karond")
option_wh2_main_def_clar_karond:set_tooltip_text("Buff/Debuff for DEF Clar Karond")
option_wh2_main_def_clar_karond:slider_set_min_max(-3, 3)
option_wh2_main_def_clar_karond:slider_set_step_size(1)
option_wh2_main_def_clar_karond:set_default_value(0)

local option_wh2_main_def_cult_of_excess = mct_mod:add_new_option ("wh2_main_def_cult_of_excess", "slider")
option_wh2_main_def_cult_of_excess:set_text("DEF Cult of Excess")
option_wh2_main_def_cult_of_excess:set_tooltip_text("Buff/Debuff for DEF Cult of Excess")
option_wh2_main_def_cult_of_excess:slider_set_min_max(-3, 3)
option_wh2_main_def_cult_of_excess:slider_set_step_size(1)
option_wh2_main_def_cult_of_excess:set_default_value(0)

local option_wh2_main_def_cult_of_pleasure = mct_mod:add_new_option ("wh2_main_def_cult_of_pleasure", "slider")
option_wh2_main_def_cult_of_pleasure:set_text("DEF Cult of Pleasure")
option_wh2_main_def_cult_of_pleasure:set_tooltip_text("Buff/Debuff for DEF Cult of Pleasure")
option_wh2_main_def_cult_of_pleasure:slider_set_min_max(-3, 3)
option_wh2_main_def_cult_of_pleasure:slider_set_step_size(1)
option_wh2_main_def_cult_of_pleasure:set_default_value(0)

local option_wh2_main_def_deadwood_sentinels = mct_mod:add_new_option ("wh2_main_def_deadwood_sentinels", "slider")
option_wh2_main_def_deadwood_sentinels:set_text("DEF Deadwood Sentinels")
option_wh2_main_def_deadwood_sentinels:set_tooltip_text("Buff/Debuff for DEF Deadwood Sentinels")
option_wh2_main_def_deadwood_sentinels:slider_set_min_max(-3, 3)
option_wh2_main_def_deadwood_sentinels:slider_set_step_size(1)
option_wh2_main_def_deadwood_sentinels:set_default_value(0)

local option_wh2_main_def_drackla_coven = mct_mod:add_new_option ("wh2_main_def_drackla_coven", "slider")
option_wh2_main_def_drackla_coven:set_text("DEF Drackla Coven")
option_wh2_main_def_drackla_coven:set_tooltip_text("Buff/Debuff for DEF Drackla Coven")
option_wh2_main_def_drackla_coven:slider_set_min_max(-3, 3)
option_wh2_main_def_drackla_coven:slider_set_step_size(1)
option_wh2_main_def_drackla_coven:set_default_value(0)

local option_wh2_main_def_ghrond = mct_mod:add_new_option ("wh2_main_def_ghrond", "slider")
option_wh2_main_def_ghrond:set_text("DEF Ghrond")
option_wh2_main_def_ghrond:set_tooltip_text("Buff/Debuff for DEF Ghrond")
option_wh2_main_def_ghrond:slider_set_min_max(-3, 3)
option_wh2_main_def_ghrond:slider_set_step_size(1)
option_wh2_main_def_ghrond:set_default_value(0)

local option_wh2_main_def_hag_graef = mct_mod:add_new_option ("wh2_main_def_hag_graef", "slider")
option_wh2_main_def_hag_graef:set_text("DEF Hag Graef")
option_wh2_main_def_hag_graef:set_tooltip_text("Buff/Debuff for DEF Hag Graef")
option_wh2_main_def_hag_graef:slider_set_min_max(-3, 3)
option_wh2_main_def_hag_graef:slider_set_step_size(1)
option_wh2_main_def_hag_graef:set_default_value(0)

local option_wh2_main_def_har_ganeth = mct_mod:add_new_option ("wh2_main_def_har_ganeth", "slider")
option_wh2_main_def_har_ganeth:set_text("DEF Har Ganeth")
option_wh2_main_def_har_ganeth:set_tooltip_text("Buff/Debuff for DEF Har Ganeth")
option_wh2_main_def_har_ganeth:slider_set_min_max(-3, 3)
option_wh2_main_def_har_ganeth:slider_set_step_size(1)
option_wh2_main_def_har_ganeth:set_default_value(0)

local option_wh2_main_def_karond_kar = mct_mod:add_new_option ("wh2_main_def_karond_kar", "slider")
option_wh2_main_def_karond_kar:set_text("DEF Karond Kar")
option_wh2_main_def_karond_kar:set_tooltip_text("Buff/Debuff for DEF Karond Kar")
option_wh2_main_def_karond_kar:slider_set_min_max(-3, 3)
option_wh2_main_def_karond_kar:slider_set_step_size(1)
option_wh2_main_def_karond_kar:set_default_value(0)

local option_wh2_main_def_naggarond = mct_mod:add_new_option ("wh2_main_def_naggarond", "slider")
option_wh2_main_def_naggarond:set_text("DEF Naggarond")
option_wh2_main_def_naggarond:set_tooltip_text("Buff/Debuff for DEF Naggarond")
option_wh2_main_def_naggarond:slider_set_min_max(-3, 3)
option_wh2_main_def_naggarond:slider_set_step_size(1)
option_wh2_main_def_naggarond:set_default_value(0)

local option_wh2_main_def_scourge_of_khaine = mct_mod:add_new_option ("wh2_main_def_scourge_of_khaine", "slider")
option_wh2_main_def_scourge_of_khaine:set_text("DEF Scourge of Khaine")
option_wh2_main_def_scourge_of_khaine:set_tooltip_text("Buff/Debuff for DEF Scourge of Khaine")
option_wh2_main_def_scourge_of_khaine:slider_set_min_max(-3, 3)
option_wh2_main_def_scourge_of_khaine:slider_set_step_size(1)
option_wh2_main_def_scourge_of_khaine:set_default_value(0)

local option_wh2_main_def_ssildra_tor = mct_mod:add_new_option ("wh2_main_def_ssildra_tor", "slider")
option_wh2_main_def_ssildra_tor:set_text("DEF Ss'ildra Tor")
option_wh2_main_def_ssildra_tor:set_tooltip_text("Buff/Debuff for DEF Ss'ildra Tor")
option_wh2_main_def_ssildra_tor:slider_set_min_max(-3, 3)
option_wh2_main_def_ssildra_tor:slider_set_step_size(1)
option_wh2_main_def_ssildra_tor:set_default_value(0)

local option_wh2_dlc11_def_the_blessed_dread = mct_mod:add_new_option ("wh2_dlc11_def_the_blessed_dread", "slider")
option_wh2_dlc11_def_the_blessed_dread:set_text("DEF The Blessed Dread")
option_wh2_dlc11_def_the_blessed_dread:set_tooltip_text("Buff/Debuff for DEF The Blessed Dread")
option_wh2_dlc11_def_the_blessed_dread:slider_set_min_max(-3, 3)
option_wh2_dlc11_def_the_blessed_dread:slider_set_step_size(1)
option_wh2_dlc11_def_the_blessed_dread:set_default_value(0)

local option_wh2_main_def_the_forgebound = mct_mod:add_new_option ("wh2_main_def_the_forgebound", "slider")
option_wh2_main_def_the_forgebound:set_text("DEF The Forgebound")
option_wh2_main_def_the_forgebound:set_tooltip_text("Buff/Debuff for DEF The Forgebound")
option_wh2_main_def_the_forgebound:slider_set_min_max(-3, 3)
option_wh2_main_def_the_forgebound:slider_set_step_size(1)
option_wh2_main_def_the_forgebound:set_default_value(0)

local option_wh_main_dwf_barak_varr = mct_mod:add_new_option ("wh_main_dwf_barak_varr", "slider")
option_wh_main_dwf_barak_varr:set_text("DWF Barak Varr")
option_wh_main_dwf_barak_varr:set_tooltip_text("Buff/Debuff for DWF Barak Varr")
option_wh_main_dwf_barak_varr:slider_set_min_max(-3, 3)
option_wh_main_dwf_barak_varr:slider_set_step_size(1)
option_wh_main_dwf_barak_varr:set_default_value(0)

local option_wh_main_dwf_karak_izor = mct_mod:add_new_option ("wh_main_dwf_karak_izor", "slider")
option_wh_main_dwf_karak_izor:set_text("DWF Clan Angrund")
option_wh_main_dwf_karak_izor:set_tooltip_text("Buff/Debuff for DWF Clan Angrund")
option_wh_main_dwf_karak_izor:slider_set_min_max(-3, 3)
option_wh_main_dwf_karak_izor:slider_set_step_size(1)
option_wh_main_dwf_karak_izor:set_default_value(0)

local option_wh2_dlc15_dwf_clan_helhein = mct_mod:add_new_option ("wh2_dlc15_dwf_clan_helhein", "slider")
option_wh2_dlc15_dwf_clan_helhein:set_text("DWF Clan Helhein")
option_wh2_dlc15_dwf_clan_helhein:set_tooltip_text("Buff/Debuff for DWF Clan Helhein")
option_wh2_dlc15_dwf_clan_helhein:slider_set_min_max(-3, 3)
option_wh2_dlc15_dwf_clan_helhein:slider_set_step_size(1)
option_wh2_dlc15_dwf_clan_helhein:set_default_value(0)

local option_wh2_main_dwf_greybeards_prospectors = mct_mod:add_new_option ("wh2_main_dwf_greybeards_prospectors", "slider")
option_wh2_main_dwf_greybeards_prospectors:set_text("DWF Greybeard's Prospectors")
option_wh2_main_dwf_greybeards_prospectors:set_tooltip_text("Buff/Debuff for DWF Greybeard's Prospectors")
option_wh2_main_dwf_greybeards_prospectors:slider_set_min_max(-3, 3)
option_wh2_main_dwf_greybeards_prospectors:slider_set_step_size(1)
option_wh2_main_dwf_greybeards_prospectors:set_default_value(0)

local option_wh_main_dwf_karak_azul = mct_mod:add_new_option ("wh_main_dwf_karak_azul", "slider")
option_wh_main_dwf_karak_azul:set_text("DWF Karak Azul")
option_wh_main_dwf_karak_azul:set_tooltip_text("Buff/Debuff for DWF Karak Azul")
option_wh_main_dwf_karak_azul:slider_set_min_max(-3, 3)
option_wh_main_dwf_karak_azul:slider_set_step_size(1)
option_wh_main_dwf_karak_azul:set_default_value(0)

local option_wh_main_dwf_karak_hirn = mct_mod:add_new_option ("wh_main_dwf_karak_hirn", "slider")
option_wh_main_dwf_karak_hirn:set_text("DWF Karak Hirn")
option_wh_main_dwf_karak_hirn:set_tooltip_text("Buff/Debuff for DWF Karak Hirn")
option_wh_main_dwf_karak_hirn:slider_set_min_max(-3, 3)
option_wh_main_dwf_karak_hirn:slider_set_step_size(1)
option_wh_main_dwf_karak_hirn:set_default_value(0)

local option_wh_main_dwf_karak_kadrin = mct_mod:add_new_option ("wh_main_dwf_karak_kadrin", "slider")
option_wh_main_dwf_karak_kadrin:set_text("DWF Karak Kadrin")
option_wh_main_dwf_karak_kadrin:set_tooltip_text("Buff/Debuff for DWF Karak Kadrin")
option_wh_main_dwf_karak_kadrin:slider_set_min_max(-3, 3)
option_wh_main_dwf_karak_kadrin:slider_set_step_size(1)
option_wh_main_dwf_karak_kadrin:set_default_value(0)

local option_wh_main_dwf_karak_norn = mct_mod:add_new_option ("wh_main_dwf_karak_norn", "slider")
option_wh_main_dwf_karak_norn:set_text("DWF Karak Norn")
option_wh_main_dwf_karak_norn:set_tooltip_text("Buff/Debuff for DWF Karak Norn")
option_wh_main_dwf_karak_norn:slider_set_min_max(-3, 3)
option_wh_main_dwf_karak_norn:slider_set_step_size(1)
option_wh_main_dwf_karak_norn:set_default_value(0)

local option_wh_main_dwf_karak_ziflin = mct_mod:add_new_option ("wh_main_dwf_karak_ziflin", "slider")
option_wh_main_dwf_karak_ziflin:set_text("DWF Karak Ziflin")
option_wh_main_dwf_karak_ziflin:set_tooltip_text("Buff/Debuff for DWF Karak Ziflin")
option_wh_main_dwf_karak_ziflin:slider_set_min_max(-3, 3)
option_wh_main_dwf_karak_ziflin:slider_set_step_size(1)
option_wh_main_dwf_karak_ziflin:set_default_value(0)

local option_wh2_main_dwf_karak_zorn = mct_mod:add_new_option ("wh2_main_dwf_karak_zorn", "slider")
option_wh2_main_dwf_karak_zorn:set_text("DWF Karak Zorn")
option_wh2_main_dwf_karak_zorn:set_tooltip_text("Buff/Debuff for DWF Karak Zorn")
option_wh2_main_dwf_karak_zorn:slider_set_min_max(-3, 3)
option_wh2_main_dwf_karak_zorn:slider_set_step_size(1)
option_wh2_main_dwf_karak_zorn:set_default_value(0)

local option_wh_main_dwf_dwarfs = mct_mod:add_new_option ("wh_main_dwf_dwarfs", "slider")
option_wh_main_dwf_dwarfs:set_text("DWF Karaz-a-Karak")
option_wh_main_dwf_dwarfs:set_tooltip_text("Buff/Debuff for DWF Karaz-a-Karak")
option_wh_main_dwf_dwarfs:slider_set_min_max(-3, 3)
option_wh_main_dwf_dwarfs:slider_set_step_size(1)
option_wh_main_dwf_dwarfs:set_default_value(0)

local option_wh_main_dwf_kraka_drak = mct_mod:add_new_option ("wh_main_dwf_kraka_drak", "slider")
option_wh_main_dwf_kraka_drak:set_text("DWF Kraka Drak")
option_wh_main_dwf_kraka_drak:set_tooltip_text("Buff/Debuff for DWF Kraka Drak")
option_wh_main_dwf_kraka_drak:slider_set_min_max(-3, 3)
option_wh_main_dwf_kraka_drak:slider_set_step_size(1)
option_wh_main_dwf_kraka_drak:set_default_value(0)

local option_wh2_main_dwf_spine_of_sotek_dwarfs = mct_mod:add_new_option ("wh2_main_dwf_spine_of_sotek_dwarfs", "slider")
option_wh2_main_dwf_spine_of_sotek_dwarfs:set_text("DWF Spine of Sotek Dwarfs")
option_wh2_main_dwf_spine_of_sotek_dwarfs:set_tooltip_text("Buff/Debuff for DWF Spine of Sotek Dwarfs")
option_wh2_main_dwf_spine_of_sotek_dwarfs:slider_set_min_max(-3, 3)
option_wh2_main_dwf_spine_of_sotek_dwarfs:slider_set_step_size(1)
option_wh2_main_dwf_spine_of_sotek_dwarfs:set_default_value(0)

local option_wh_main_dwf_zhufbar = mct_mod:add_new_option ("wh_main_dwf_zhufbar", "slider")
option_wh_main_dwf_zhufbar:set_text("DWF Zhufbar")
option_wh_main_dwf_zhufbar:set_tooltip_text("Buff/Debuff for DWF Zhufbar")
option_wh_main_dwf_zhufbar:slider_set_min_max(-3, 3)
option_wh_main_dwf_zhufbar:slider_set_step_size(1)
option_wh_main_dwf_zhufbar:set_default_value(0)

local option_wh_main_emp_averland = mct_mod:add_new_option ("wh_main_emp_averland", "slider")
option_wh_main_emp_averland:set_text("EMP Averland")
option_wh_main_emp_averland:set_tooltip_text("Buff/Debuff for EMP Averland")
option_wh_main_emp_averland:slider_set_min_max(-3, 3)
option_wh_main_emp_averland:slider_set_step_size(1)
option_wh_main_emp_averland:set_default_value(0)

local option_wh_main_emp_hochland = mct_mod:add_new_option ("wh_main_emp_hochland", "slider")
option_wh_main_emp_hochland:set_text("EMP Hochland")
option_wh_main_emp_hochland:set_tooltip_text("Buff/Debuff for EMP Hochland")
option_wh_main_emp_hochland:slider_set_min_max(-3, 3)
option_wh_main_emp_hochland:slider_set_step_size(1)
option_wh_main_emp_hochland:set_default_value(0)

local option_wh_main_emp_marienburg = mct_mod:add_new_option ("wh_main_emp_marienburg", "slider")
option_wh_main_emp_marienburg:set_text("EMP Marienburg")
option_wh_main_emp_marienburg:set_tooltip_text("Buff/Debuff for EMP Marienburg")
option_wh_main_emp_marienburg:slider_set_min_max(-3, 3)
option_wh_main_emp_marienburg:slider_set_step_size(1)
option_wh_main_emp_marienburg:set_default_value(0)

local option_wh_main_emp_middenland = mct_mod:add_new_option ("wh_main_emp_middenland", "slider")
option_wh_main_emp_middenland:set_text("EMP Middenland")
option_wh_main_emp_middenland:set_tooltip_text("Buff/Debuff for EMP Middenland")
option_wh_main_emp_middenland:slider_set_min_max(-3, 3)
option_wh_main_emp_middenland:slider_set_step_size(1)
option_wh_main_emp_middenland:set_default_value(0)

local option_wh2_main_emp_new_world_colonies = mct_mod:add_new_option ("wh2_main_emp_new_world_colonies", "slider")
option_wh2_main_emp_new_world_colonies:set_text("EMP New World Colonies")
option_wh2_main_emp_new_world_colonies:set_tooltip_text("Buff/Debuff for EMP New World Colonies")
option_wh2_main_emp_new_world_colonies:slider_set_min_max(-3, 3)
option_wh2_main_emp_new_world_colonies:slider_set_step_size(1)
option_wh2_main_emp_new_world_colonies:set_default_value(0)

local option_wh_main_emp_nordland = mct_mod:add_new_option ("wh_main_emp_nordland", "slider")
option_wh_main_emp_nordland:set_text("EMP Nordland")
option_wh_main_emp_nordland:set_tooltip_text("Buff/Debuff for EMP Nordland")
option_wh_main_emp_nordland:slider_set_min_max(-3, 3)
option_wh_main_emp_nordland:slider_set_step_size(1)
option_wh_main_emp_nordland:set_default_value(0)

local option_wh_main_emp_ostermark = mct_mod:add_new_option ("wh_main_emp_ostermark", "slider")
option_wh_main_emp_ostermark:set_text("EMP Ostermark")
option_wh_main_emp_ostermark:set_tooltip_text("Buff/Debuff for EMP Ostermark")
option_wh_main_emp_ostermark:slider_set_min_max(-3, 3)
option_wh_main_emp_ostermark:slider_set_step_size(1)
option_wh_main_emp_ostermark:set_default_value(0)

local option_wh_main_emp_ostland = mct_mod:add_new_option ("wh_main_emp_ostland", "slider")
option_wh_main_emp_ostland:set_text("EMP Ostland")
option_wh_main_emp_ostland:set_tooltip_text("Buff/Debuff for EMP Ostland")
option_wh_main_emp_ostland:slider_set_min_max(-3, 3)
option_wh_main_emp_ostland:slider_set_step_size(1)
option_wh_main_emp_ostland:set_default_value(0)

local option_wh_main_emp_empire = mct_mod:add_new_option ("wh_main_emp_empire", "slider")
option_wh_main_emp_empire:set_text("EMP Reikland")
option_wh_main_emp_empire:set_tooltip_text("Buff/Debuff for EMP Reikland")
option_wh_main_emp_empire:slider_set_min_max(-3, 3)
option_wh_main_emp_empire:slider_set_step_size(1)
option_wh_main_emp_empire:set_default_value(0)

local option_wh_main_emp_stirland = mct_mod:add_new_option ("wh_main_emp_stirland", "slider")
option_wh_main_emp_stirland:set_text("EMP Stirland")
option_wh_main_emp_stirland:set_tooltip_text("Buff/Debuff for EMP Stirland")
option_wh_main_emp_stirland:slider_set_min_max(-3, 3)
option_wh_main_emp_stirland:slider_set_step_size(1)
option_wh_main_emp_stirland:set_default_value(0)

local option_wh2_main_emp_sudenburg = mct_mod:add_new_option ("wh2_main_emp_sudenburg", "slider")
option_wh2_main_emp_sudenburg:set_text("EMP Sudenburg")
option_wh2_main_emp_sudenburg:set_tooltip_text("Buff/Debuff for EMP Sudenburg")
option_wh2_main_emp_sudenburg:slider_set_min_max(-3, 3)
option_wh2_main_emp_sudenburg:slider_set_step_size(1)
option_wh2_main_emp_sudenburg:set_default_value(0)

local option_wh_main_emp_talabecland = mct_mod:add_new_option ("wh_main_emp_talabecland", "slider")
option_wh_main_emp_talabecland:set_text("EMP Talabecland")
option_wh_main_emp_talabecland:set_tooltip_text("Buff/Debuff for EMP Talabecland")
option_wh_main_emp_talabecland:slider_set_min_max(-3, 3)
option_wh_main_emp_talabecland:slider_set_step_size(1)
option_wh_main_emp_talabecland:set_default_value(0)

local option_wh2_dlc13_emp_golden_order = mct_mod:add_new_option ("wh2_dlc13_emp_golden_order", "slider")
option_wh2_dlc13_emp_golden_order:set_text("EMP The Golden Order")
option_wh2_dlc13_emp_golden_order:set_tooltip_text("Buff/Debuff for EMP The Golden Order")
option_wh2_dlc13_emp_golden_order:slider_set_min_max(-3, 3)
option_wh2_dlc13_emp_golden_order:slider_set_step_size(1)
option_wh2_dlc13_emp_golden_order:set_default_value(0)

local option_wh2_dlc13_emp_the_huntmarshals_expedition = mct_mod:add_new_option ("wh2_dlc13_emp_the_huntmarshals_expedition", "slider")
option_wh2_dlc13_emp_the_huntmarshals_expedition:set_text("EMP The Huntsmarshal's Expedition")
option_wh2_dlc13_emp_the_huntmarshals_expedition:set_tooltip_text("Buff/Debuff for EMP The Huntsmarshal's Expedition")
option_wh2_dlc13_emp_the_huntmarshals_expedition:slider_set_min_max(-3, 3)
option_wh2_dlc13_emp_the_huntmarshals_expedition:slider_set_step_size(1)
option_wh2_dlc13_emp_the_huntmarshals_expedition:set_default_value(0)

local option_wh_main_emp_wissenland = mct_mod:add_new_option ("wh_main_emp_wissenland", "slider")
option_wh_main_emp_wissenland:set_text("EMP Wissenland")
option_wh_main_emp_wissenland:set_tooltip_text("Buff/Debuff for EMP Wissenland")
option_wh_main_emp_wissenland:slider_set_min_max(-3, 3)
option_wh_main_emp_wissenland:slider_set_step_size(1)
option_wh_main_emp_wissenland:set_default_value(0)

local option_wh2_main_grn_arachnos = mct_mod:add_new_option ("wh2_main_grn_arachnos", "slider")
option_wh2_main_grn_arachnos:set_text("GRN Arachnos")
option_wh2_main_grn_arachnos:set_tooltip_text("Buff/Debuff for GRN Arachnos")
option_wh2_main_grn_arachnos:slider_set_min_max(-3, 3)
option_wh2_main_grn_arachnos:slider_set_step_size(1)
option_wh2_main_grn_arachnos:set_default_value(0)

local option_wh_main_grn_black_venom = mct_mod:add_new_option ("wh_main_grn_black_venom", "slider")
option_wh_main_grn_black_venom:set_text("GRN Black Venom")
option_wh_main_grn_black_venom:set_tooltip_text("Buff/Debuff for GRN Black Venom")
option_wh_main_grn_black_venom:slider_set_min_max(-3, 3)
option_wh_main_grn_black_venom:slider_set_step_size(1)
option_wh_main_grn_black_venom:set_default_value(0)

local option_wh_main_grn_bloody_spearz = mct_mod:add_new_option ("wh_main_grn_bloody_spearz", "slider")
option_wh_main_grn_bloody_spearz:set_text("GRN Bloody Spearz")
option_wh_main_grn_bloody_spearz:set_tooltip_text("Buff/Debuff for GRN Bloody Spearz")
option_wh_main_grn_bloody_spearz:slider_set_min_max(-3, 3)
option_wh_main_grn_bloody_spearz:slider_set_step_size(1)
option_wh_main_grn_bloody_spearz:set_default_value(0)

local option_wh2_main_grn_blue_vipers = mct_mod:add_new_option ("wh2_main_grn_blue_vipers", "slider")
option_wh2_main_grn_blue_vipers:set_text("GRN Blue Vipers")
option_wh2_main_grn_blue_vipers:set_tooltip_text("Buff/Debuff for GRN Blue Vipers")
option_wh2_main_grn_blue_vipers:slider_set_min_max(-3, 3)
option_wh2_main_grn_blue_vipers:slider_set_step_size(1)
option_wh2_main_grn_blue_vipers:set_default_value(0)

local option_wh2_dlc15_grn_bonerattlaz = mct_mod:add_new_option ("wh2_dlc15_grn_bonerattlaz", "slider")
option_wh2_dlc15_grn_bonerattlaz:set_text("GRN Bonerattlaz")
option_wh2_dlc15_grn_bonerattlaz:set_tooltip_text("Buff/Debuff for GRN Bonerattlaz")
option_wh2_dlc15_grn_bonerattlaz:slider_set_min_max(-3, 3)
option_wh2_dlc15_grn_bonerattlaz:slider_set_step_size(1)
option_wh2_dlc15_grn_bonerattlaz:set_default_value(0)

local option_wh2_dlc15_grn_broken_axe = mct_mod:add_new_option ("wh2_dlc15_grn_broken_axe", "slider")
option_wh2_dlc15_grn_broken_axe:set_text("GRN Broken Axe")
option_wh2_dlc15_grn_broken_axe:set_tooltip_text("Buff/Debuff for GRN Broken Axe")
option_wh2_dlc15_grn_broken_axe:slider_set_min_max(-3, 3)
option_wh2_dlc15_grn_broken_axe:slider_set_step_size(1)
option_wh2_dlc15_grn_broken_axe:set_default_value(0)

local option_wh_main_grn_broken_nose = mct_mod:add_new_option ("wh_main_grn_broken_nose", "slider")
option_wh_main_grn_broken_nose:set_text("GRN Broken Nose")
option_wh_main_grn_broken_nose:set_tooltip_text("Buff/Debuff for GRN Broken Nose")
option_wh_main_grn_broken_nose:slider_set_min_max(-3, 3)
option_wh_main_grn_broken_nose:slider_set_step_size(1)
option_wh_main_grn_broken_nose:set_default_value(0)

local option_wh_main_grn_crooked_moon = mct_mod:add_new_option ("wh_main_grn_crooked_moon", "slider")
option_wh_main_grn_crooked_moon:set_text("GRN Crooked Moon")
option_wh_main_grn_crooked_moon:set_tooltip_text("Buff/Debuff for GRN Crooked Moon")
option_wh_main_grn_crooked_moon:slider_set_min_max(-3, 3)
option_wh_main_grn_crooked_moon:slider_set_step_size(1)
option_wh_main_grn_crooked_moon:set_default_value(0)

local option_wh_main_grn_necksnappers = mct_mod:add_new_option ("wh_main_grn_necksnappers", "slider")
option_wh_main_grn_necksnappers:set_text("GRN Crooked Moon Mutinous Gits")
option_wh_main_grn_necksnappers:set_tooltip_text("Buff/Debuff for GRN Crooked Moon Mutinous Gits")
option_wh_main_grn_necksnappers:slider_set_min_max(-3, 3)
option_wh_main_grn_necksnappers:slider_set_step_size(1)
option_wh_main_grn_necksnappers:set_default_value(0)

local option_wh_main_grn_greenskins = mct_mod:add_new_option ("wh_main_grn_greenskins", "slider")
option_wh_main_grn_greenskins:set_text("GRN Grimgor's 'Ardboyz")
option_wh_main_grn_greenskins:set_tooltip_text("Buff/Debuff for GRN Grimgor's 'Ardboyz")
option_wh_main_grn_greenskins:slider_set_min_max(-3, 3)
option_wh_main_grn_greenskins:slider_set_step_size(1)
option_wh_main_grn_greenskins:set_default_value(0)

local option_wh2_dlc12_grn_leaf_cutterz_tribe = mct_mod:add_new_option ("wh2_dlc12_grn_leaf_cutterz_tribe", "slider")
option_wh2_dlc12_grn_leaf_cutterz_tribe:set_text("GRN Leaf-Cutterz Tribe")
option_wh2_dlc12_grn_leaf_cutterz_tribe:set_tooltip_text("Buff/Debuff for GRN Leaf-Cutterz Tribe")
option_wh2_dlc12_grn_leaf_cutterz_tribe:slider_set_min_max(-3, 3)
option_wh2_dlc12_grn_leaf_cutterz_tribe:slider_set_step_size(1)
option_wh2_dlc12_grn_leaf_cutterz_tribe:set_default_value(0)

local option_wh2_dlc14_grn_red_cloud = mct_mod:add_new_option ("wh2_dlc14_grn_red_cloud", "slider")
option_wh2_dlc14_grn_red_cloud:set_text("GRN Red Cloud")
option_wh2_dlc14_grn_red_cloud:set_tooltip_text("Buff/Debuff for GRN Red Cloud")
option_wh2_dlc14_grn_red_cloud:slider_set_min_max(-3, 3)
option_wh2_dlc14_grn_red_cloud:slider_set_step_size(1)
option_wh2_dlc14_grn_red_cloud:set_default_value(0)

local option_wh_main_grn_red_eye = mct_mod:add_new_option ("wh_main_grn_red_eye", "slider")
option_wh_main_grn_red_eye:set_text("GRN Red Eye")
option_wh_main_grn_red_eye:set_tooltip_text("Buff/Debuff for GRN Red Eye")
option_wh_main_grn_red_eye:slider_set_min_max(-3, 3)
option_wh_main_grn_red_eye:slider_set_step_size(1)
option_wh_main_grn_red_eye:set_default_value(0)

local option_wh_main_grn_red_fangs = mct_mod:add_new_option ("wh_main_grn_red_fangs", "slider")
option_wh_main_grn_red_fangs:set_text("GRN Red Fangs")
option_wh_main_grn_red_fangs:set_tooltip_text("Buff/Debuff for GRN Red Fangs")
option_wh_main_grn_red_fangs:slider_set_min_max(-3, 3)
option_wh_main_grn_red_fangs:slider_set_step_size(1)
option_wh_main_grn_red_fangs:set_default_value(0)

local option_wh_main_grn_scabby_eye = mct_mod:add_new_option ("wh_main_grn_scabby_eye", "slider")
option_wh_main_grn_scabby_eye:set_text("GRN Scabby Eye")
option_wh_main_grn_scabby_eye:set_tooltip_text("Buff/Debuff for GRN Scabby Eye")
option_wh_main_grn_scabby_eye:slider_set_min_max(-3, 3)
option_wh_main_grn_scabby_eye:slider_set_step_size(1)
option_wh_main_grn_scabby_eye:set_default_value(0)

local option_wh2_dlc15_grn_skull_crag = mct_mod:add_new_option ("wh2_dlc15_grn_skull_crag", "slider")
option_wh2_dlc15_grn_skull_crag:set_text("GRN Skull Crag")
option_wh2_dlc15_grn_skull_crag:set_tooltip_text("Buff/Debuff for GRN Skull Crag")
option_wh2_dlc15_grn_skull_crag:slider_set_min_max(-3, 3)
option_wh2_dlc15_grn_skull_crag:slider_set_step_size(1)
option_wh2_dlc15_grn_skull_crag:set_default_value(0)

local option_wh_main_grn_skull_takerz = mct_mod:add_new_option ("wh_main_grn_skull-takerz", "slider")
option_wh_main_grn_skull_takerz:set_text("GRN Skull-takerz")
option_wh_main_grn_skull_takerz:set_tooltip_text("Buff/Debuff for GRN Skull-takerz")
option_wh_main_grn_skull_takerz:slider_set_min_max(-3, 3)
option_wh_main_grn_skull_takerz:slider_set_step_size(1)
option_wh_main_grn_skull_takerz:set_default_value(0)

local option_wh_main_grn_skullsmasherz = mct_mod:add_new_option ("wh_main_grn_skullsmasherz", "slider")
option_wh_main_grn_skullsmasherz:set_text("GRN Skullsmasherz")
option_wh_main_grn_skullsmasherz:set_tooltip_text("Buff/Debuff for GRN Skullsmasherz")
option_wh_main_grn_skullsmasherz:slider_set_min_max(-3, 3)
option_wh_main_grn_skullsmasherz:slider_set_step_size(1)
option_wh_main_grn_skullsmasherz:set_default_value(0)

local option_wh_main_grn_teef_snatchaz = mct_mod:add_new_option ("wh_main_grn_teef_snatchaz", "slider")
option_wh_main_grn_teef_snatchaz:set_text("GRN Teef Snatchaz")
option_wh_main_grn_teef_snatchaz:set_tooltip_text("Buff/Debuff for GRN Teef Snatchaz")
option_wh_main_grn_teef_snatchaz:slider_set_min_max(-3, 3)
option_wh_main_grn_teef_snatchaz:slider_set_step_size(1)
option_wh_main_grn_teef_snatchaz:set_default_value(0)

local option_wh_main_grn_orcs_of_the_bloody_hand = mct_mod:add_new_option ("wh_main_grn_orcs_of_the_bloody_hand", "slider")
option_wh_main_grn_orcs_of_the_bloody_hand:set_text("GRN The Bloody Handz")
option_wh_main_grn_orcs_of_the_bloody_hand:set_tooltip_text("Buff/Debuff for GRN The Bloody Handz")
option_wh_main_grn_orcs_of_the_bloody_hand:slider_set_min_max(-3, 3)
option_wh_main_grn_orcs_of_the_bloody_hand:slider_set_step_size(1)
option_wh_main_grn_orcs_of_the_bloody_hand:set_default_value(0)

local option_wh_main_grn_top_knotz = mct_mod:add_new_option ("wh_main_grn_top_knotz", "slider")
option_wh_main_grn_top_knotz:set_text("GRN Top Knotz")
option_wh_main_grn_top_knotz:set_tooltip_text("Buff/Debuff for GRN Top Knotz")
option_wh_main_grn_top_knotz:slider_set_min_max(-3, 3)
option_wh_main_grn_top_knotz:slider_set_step_size(1)
option_wh_main_grn_top_knotz:set_default_value(0)

local option_wh2_main_hef_avelorn = mct_mod:add_new_option ("wh2_main_hef_avelorn", "slider")
option_wh2_main_hef_avelorn:set_text("HEF Avelorn")
option_wh2_main_hef_avelorn:set_tooltip_text("Buff/Debuff for HEF Avelorn")
option_wh2_main_hef_avelorn:slider_set_min_max(-3, 3)
option_wh2_main_hef_avelorn:slider_set_step_size(1)
option_wh2_main_hef_avelorn:set_default_value(0)

local option_wh2_main_hef_caledor = mct_mod:add_new_option ("wh2_main_hef_caledor", "slider")
option_wh2_main_hef_caledor:set_text("HEF Caledor")
option_wh2_main_hef_caledor:set_tooltip_text("Buff/Debuff for HEF Caledor")
option_wh2_main_hef_caledor:slider_set_min_max(-3, 3)
option_wh2_main_hef_caledor:slider_set_step_size(1)
option_wh2_main_hef_caledor:set_default_value(0)

local option_wh2_main_hef_chrace = mct_mod:add_new_option ("wh2_main_hef_chrace", "slider")
option_wh2_main_hef_chrace:set_text("HEF Chrace")
option_wh2_main_hef_chrace:set_tooltip_text("Buff/Debuff for HEF Chrace")
option_wh2_main_hef_chrace:slider_set_min_max(-3, 3)
option_wh2_main_hef_chrace:slider_set_step_size(1)
option_wh2_main_hef_chrace:set_default_value(0)

local option_wh2_main_hef_citadel_of_dusk = mct_mod:add_new_option ("wh2_main_hef_citadel_of_dusk", "slider")
option_wh2_main_hef_citadel_of_dusk:set_text("HEF Citadel of Dusk")
option_wh2_main_hef_citadel_of_dusk:set_tooltip_text("Buff/Debuff for HEF Citadel of Dusk")
option_wh2_main_hef_citadel_of_dusk:slider_set_min_max(-3, 3)
option_wh2_main_hef_citadel_of_dusk:slider_set_step_size(1)
option_wh2_main_hef_citadel_of_dusk:set_default_value(0)

local option_wh2_main_hef_cothique = mct_mod:add_new_option ("wh2_main_hef_cothique", "slider")
option_wh2_main_hef_cothique:set_text("HEF Cothique")
option_wh2_main_hef_cothique:set_tooltip_text("Buff/Debuff for HEF Cothique")
option_wh2_main_hef_cothique:slider_set_min_max(-3, 3)
option_wh2_main_hef_cothique:slider_set_step_size(1)
option_wh2_main_hef_cothique:set_default_value(0)

local option_wh2_main_hef_eataine = mct_mod:add_new_option ("wh2_main_hef_eataine", "slider")
option_wh2_main_hef_eataine:set_text("HEF Eataine")
option_wh2_main_hef_eataine:set_tooltip_text("Buff/Debuff for HEF Eataine")
option_wh2_main_hef_eataine:slider_set_min_max(-3, 3)
option_wh2_main_hef_eataine:slider_set_step_size(1)
option_wh2_main_hef_eataine:set_default_value(0)

local option_wh2_main_hef_ellyrion = mct_mod:add_new_option ("wh2_main_hef_ellyrion", "slider")
option_wh2_main_hef_ellyrion:set_text("HEF Ellyrion")
option_wh2_main_hef_ellyrion:set_tooltip_text("Buff/Debuff for HEF Ellyrion")
option_wh2_main_hef_ellyrion:slider_set_min_max(-3, 3)
option_wh2_main_hef_ellyrion:slider_set_step_size(1)
option_wh2_main_hef_ellyrion:set_default_value(0)

local option_wh2_main_hef_fortress_of_dawn = mct_mod:add_new_option ("wh2_main_hef_fortress_of_dawn", "slider")
option_wh2_main_hef_fortress_of_dawn:set_text("HEF Fortress of Dawn")
option_wh2_main_hef_fortress_of_dawn:set_tooltip_text("Buff/Debuff for HEF Fortress of Dawn")
option_wh2_main_hef_fortress_of_dawn:slider_set_min_max(-3, 3)
option_wh2_main_hef_fortress_of_dawn:slider_set_step_size(1)
option_wh2_main_hef_fortress_of_dawn:set_default_value(0)

local option_wh2_dlc15_hef_imrik = mct_mod:add_new_option ("wh2_dlc15_hef_imrik", "slider")
option_wh2_dlc15_hef_imrik:set_text("HEF Knights of Caledor")
option_wh2_dlc15_hef_imrik:set_tooltip_text("Buff/Debuff for HEF Knights of Caledor")
option_wh2_dlc15_hef_imrik:slider_set_min_max(-3, 3)
option_wh2_dlc15_hef_imrik:slider_set_step_size(1)
option_wh2_dlc15_hef_imrik:set_default_value(0)

local option_wh2_main_hef_nagarythe = mct_mod:add_new_option ("wh2_main_hef_nagarythe", "slider")
option_wh2_main_hef_nagarythe:set_text("HEF Nagarythe")
option_wh2_main_hef_nagarythe:set_tooltip_text("Buff/Debuff for HEF Nagarythe")
option_wh2_main_hef_nagarythe:slider_set_min_max(-3, 3)
option_wh2_main_hef_nagarythe:slider_set_step_size(1)
option_wh2_main_hef_nagarythe:set_default_value(0)

local option_wh2_main_hef_order_of_loremasters = mct_mod:add_new_option ("wh2_main_hef_order_of_loremasters", "slider")
option_wh2_main_hef_order_of_loremasters:set_text("HEF Order of Loremasters")
option_wh2_main_hef_order_of_loremasters:set_tooltip_text("Buff/Debuff for HEF Order of Loremasters")
option_wh2_main_hef_order_of_loremasters:slider_set_min_max(-3, 3)
option_wh2_main_hef_order_of_loremasters:slider_set_step_size(1)
option_wh2_main_hef_order_of_loremasters:set_default_value(0)

local option_wh2_main_hef_saphery = mct_mod:add_new_option ("wh2_main_hef_saphery", "slider")
option_wh2_main_hef_saphery:set_text("HEF Saphery")
option_wh2_main_hef_saphery:set_tooltip_text("Buff/Debuff for HEF Saphery")
option_wh2_main_hef_saphery:slider_set_min_max(-3, 3)
option_wh2_main_hef_saphery:slider_set_step_size(1)
option_wh2_main_hef_saphery:set_default_value(0)

local option_wh2_main_hef_tiranoc = mct_mod:add_new_option ("wh2_main_hef_tiranoc", "slider")
option_wh2_main_hef_tiranoc:set_text("HEF Tiranoc")
option_wh2_main_hef_tiranoc:set_tooltip_text("Buff/Debuff for HEF Tiranoc")
option_wh2_main_hef_tiranoc:slider_set_min_max(-3, 3)
option_wh2_main_hef_tiranoc:slider_set_step_size(1)
option_wh2_main_hef_tiranoc:set_default_value(0)

local option_wh2_main_hef_tor_elasor = mct_mod:add_new_option ("wh2_main_hef_tor_elasor", "slider")
option_wh2_main_hef_tor_elasor:set_text("HEF Tor Elasor")
option_wh2_main_hef_tor_elasor:set_tooltip_text("Buff/Debuff for HEF Tor Elasor")
option_wh2_main_hef_tor_elasor:slider_set_min_max(-3, 3)
option_wh2_main_hef_tor_elasor:slider_set_step_size(1)
option_wh2_main_hef_tor_elasor:set_default_value(0)

local option_wh2_main_hef_yvresse = mct_mod:add_new_option ("wh2_main_hef_yvresse", "slider")
option_wh2_main_hef_yvresse:set_text("HEF Yvresse")
option_wh2_main_hef_yvresse:set_tooltip_text("Buff/Debuff for HEF Yvresse")
option_wh2_main_hef_yvresse:slider_set_min_max(-3, 3)
option_wh2_main_hef_yvresse:slider_set_step_size(1)
option_wh2_main_hef_yvresse:set_default_value(0)

local option_wh2_dlc13_lzd_avengers = mct_mod:add_new_option ("wh2_dlc13_lzd_avengers", "slider")
option_wh2_dlc13_lzd_avengers:set_text("LZD Children of the Old Ones")
option_wh2_dlc13_lzd_avengers:set_tooltip_text("Buff/Debuff for LZD Children of the Old Ones")
option_wh2_dlc13_lzd_avengers:slider_set_min_max(-3, 3)
option_wh2_dlc13_lzd_avengers:slider_set_step_size(1)
option_wh2_dlc13_lzd_avengers:set_default_value(0)

local option_wh2_dlc12_lzd_cult_of_sotek = mct_mod:add_new_option ("wh2_dlc12_lzd_cult_of_sotek", "slider")
option_wh2_dlc12_lzd_cult_of_sotek:set_text("LZD Cult of Sotek")
option_wh2_dlc12_lzd_cult_of_sotek:set_tooltip_text("Buff/Debuff for LZD Cult of Sotek")
option_wh2_dlc12_lzd_cult_of_sotek:slider_set_min_max(-3, 3)
option_wh2_dlc12_lzd_cult_of_sotek:slider_set_step_size(1)
option_wh2_dlc12_lzd_cult_of_sotek:set_default_value(0)

local option_wh2_dlc13_lzd_defenders_of_the_great_plan = mct_mod:add_new_option ("wh2_dlc13_lzd_defenders_of_the_great_plan", "slider")
option_wh2_dlc13_lzd_defenders_of_the_great_plan:set_text("LZD Defenders of the Great Plan")
option_wh2_dlc13_lzd_defenders_of_the_great_plan:set_tooltip_text("Buff/Debuff for LZD Defenders of the Great Plan")
option_wh2_dlc13_lzd_defenders_of_the_great_plan:slider_set_min_max(-3, 3)
option_wh2_dlc13_lzd_defenders_of_the_great_plan:slider_set_step_size(1)
option_wh2_dlc13_lzd_defenders_of_the_great_plan:set_default_value(0)

local option_wh2_main_lzd_hexoatl = mct_mod:add_new_option ("wh2_main_lzd_hexoatl", "slider")
option_wh2_main_lzd_hexoatl:set_text("LZD Hexoatl")
option_wh2_main_lzd_hexoatl:set_tooltip_text("Buff/Debuff for LZD Hexoatl")
option_wh2_main_lzd_hexoatl:slider_set_min_max(-3, 3)
option_wh2_main_lzd_hexoatl:slider_set_step_size(1)
option_wh2_main_lzd_hexoatl:set_default_value(0)

local option_wh2_main_lzd_itza = mct_mod:add_new_option ("wh2_main_lzd_itza", "slider")
option_wh2_main_lzd_itza:set_text("LZD Itza")
option_wh2_main_lzd_itza:set_tooltip_text("Buff/Debuff for LZD Itza")
option_wh2_main_lzd_itza:slider_set_min_max(-3, 3)
option_wh2_main_lzd_itza:slider_set_step_size(1)
option_wh2_main_lzd_itza:set_default_value(0)

local option_wh2_main_lzd_last_defenders = mct_mod:add_new_option ("wh2_main_lzd_last_defenders", "slider")
option_wh2_main_lzd_last_defenders:set_text("LZD Last Defenders")
option_wh2_main_lzd_last_defenders:set_tooltip_text("Buff/Debuff for LZD Last Defenders")
option_wh2_main_lzd_last_defenders:slider_set_min_max(-3, 3)
option_wh2_main_lzd_last_defenders:slider_set_step_size(1)
option_wh2_main_lzd_last_defenders:set_default_value(0)

local option_wh2_main_lzd_sentinels_of_xeti = mct_mod:add_new_option ("wh2_main_lzd_sentinels_of_xeti", "slider")
option_wh2_main_lzd_sentinels_of_xeti:set_text("LZD Sentinels of Xeti")
option_wh2_main_lzd_sentinels_of_xeti:set_tooltip_text("Buff/Debuff for LZD Sentinels of Xeti")
option_wh2_main_lzd_sentinels_of_xeti:slider_set_min_max(-3, 3)
option_wh2_main_lzd_sentinels_of_xeti:slider_set_step_size(1)
option_wh2_main_lzd_sentinels_of_xeti:set_default_value(0)

local option_wh2_main_lzd_southern_sentinels = mct_mod:add_new_option ("wh2_main_lzd_southern_sentinels", "slider")
option_wh2_main_lzd_southern_sentinels:set_text("LZD Southern Sentinels")
option_wh2_main_lzd_southern_sentinels:set_tooltip_text("Buff/Debuff for LZD Southern Sentinels")
option_wh2_main_lzd_southern_sentinels:slider_set_min_max(-3, 3)
option_wh2_main_lzd_southern_sentinels:slider_set_step_size(1)
option_wh2_main_lzd_southern_sentinels:set_default_value(0)

local option_wh2_dlc13_lzd_spirits_of_the_jungle = mct_mod:add_new_option ("wh2_dlc13_lzd_spirits_of_the_jungle", "slider")
option_wh2_dlc13_lzd_spirits_of_the_jungle:set_text("LZD Spirit of the Jungle")
option_wh2_dlc13_lzd_spirits_of_the_jungle:set_tooltip_text("Buff/Debuff for LZD Spirit of the Jungle")
option_wh2_dlc13_lzd_spirits_of_the_jungle:slider_set_min_max(-3, 3)
option_wh2_dlc13_lzd_spirits_of_the_jungle:slider_set_step_size(1)
option_wh2_dlc13_lzd_spirits_of_the_jungle:set_default_value(0)

local option_wh2_main_lzd_teotiqua = mct_mod:add_new_option ("wh2_main_lzd_teotiqua", "slider")
option_wh2_main_lzd_teotiqua:set_text("LZD Teotiqua")
option_wh2_main_lzd_teotiqua:set_tooltip_text("Buff/Debuff for LZD Teotiqua")
option_wh2_main_lzd_teotiqua:slider_set_min_max(-3, 3)
option_wh2_main_lzd_teotiqua:slider_set_step_size(1)
option_wh2_main_lzd_teotiqua:set_default_value(0)

local option_wh2_main_lzd_tlaqua = mct_mod:add_new_option ("wh2_main_lzd_tlaqua", "slider")
option_wh2_main_lzd_tlaqua:set_text("LZD Tlaqua")
option_wh2_main_lzd_tlaqua:set_tooltip_text("Buff/Debuff for LZD Tlaqua")
option_wh2_main_lzd_tlaqua:slider_set_min_max(-3, 3)
option_wh2_main_lzd_tlaqua:slider_set_step_size(1)
option_wh2_main_lzd_tlaqua:set_default_value(0)

local option_wh2_main_lzd_tlaxtlan = mct_mod:add_new_option ("wh2_main_lzd_tlaxtlan", "slider")
option_wh2_main_lzd_tlaxtlan:set_text("LZD Tlaxtlan")
option_wh2_main_lzd_tlaxtlan:set_tooltip_text("Buff/Debuff for LZD Tlaxtlan")
option_wh2_main_lzd_tlaxtlan:slider_set_min_max(-3, 3)
option_wh2_main_lzd_tlaxtlan:slider_set_step_size(1)
option_wh2_main_lzd_tlaxtlan:set_default_value(0)

local option_wh2_main_lzd_xlanhuapec = mct_mod:add_new_option ("wh2_main_lzd_xlanhuapec", "slider")
option_wh2_main_lzd_xlanhuapec:set_text("LZD Xlanhuapec")
option_wh2_main_lzd_xlanhuapec:set_tooltip_text("Buff/Debuff for LZD Xlanhuapec")
option_wh2_main_lzd_xlanhuapec:slider_set_min_max(-3, 3)
option_wh2_main_lzd_xlanhuapec:slider_set_step_size(1)
option_wh2_main_lzd_xlanhuapec:set_default_value(0)

local option_wh2_main_lzd_zlatan = mct_mod:add_new_option ("wh2_main_lzd_zlatan", "slider")
option_wh2_main_lzd_zlatan:set_text("LZD Zlatlan")
option_wh2_main_lzd_zlatan:set_tooltip_text("Buff/Debuff for LZD Zlatlan")
option_wh2_main_lzd_zlatan:slider_set_min_max(-3, 3)
option_wh2_main_lzd_zlatan:slider_set_step_size(1)
option_wh2_main_lzd_zlatan:set_default_value(0)

local option_wh_main_nor_aesling = mct_mod:add_new_option ("wh_main_nor_aesling", "slider")
option_wh_main_nor_aesling:set_text("NOR Aesling")
option_wh_main_nor_aesling:set_tooltip_text("Buff/Debuff for NOR Aesling")
option_wh_main_nor_aesling:slider_set_min_max(-3, 3)
option_wh_main_nor_aesling:slider_set_step_size(1)
option_wh_main_nor_aesling:set_default_value(0)

local option_wh2_main_nor_aghol = mct_mod:add_new_option ("wh2_main_nor_aghol", "slider")
option_wh2_main_nor_aghol:set_text("NOR Aghol")
option_wh2_main_nor_aghol:set_tooltip_text("Buff/Debuff for NOR Aghol")
option_wh2_main_nor_aghol:slider_set_min_max(-3, 3)
option_wh2_main_nor_aghol:slider_set_step_size(1)
option_wh2_main_nor_aghol:set_default_value(0)

local option_wh_main_nor_baersonling = mct_mod:add_new_option ("wh_main_nor_baersonling", "slider")
option_wh_main_nor_baersonling:set_text("NOR Baersonling")
option_wh_main_nor_baersonling:set_tooltip_text("Buff/Debuff for NOR Baersonling")
option_wh_main_nor_baersonling:slider_set_min_max(-3, 3)
option_wh_main_nor_baersonling:slider_set_step_size(1)
option_wh_main_nor_baersonling:set_default_value(0)

local option_wh_main_nor_bjornling = mct_mod:add_new_option ("wh_main_nor_bjornling", "slider")
option_wh_main_nor_bjornling:set_text("NOR Bjornling")
option_wh_main_nor_bjornling:set_tooltip_text("Buff/Debuff for NOR Bjornling")
option_wh_main_nor_bjornling:slider_set_min_max(-3, 3)
option_wh_main_nor_bjornling:slider_set_step_size(1)
option_wh_main_nor_bjornling:set_default_value(0)

local option_wh_dlc08_nor_goromadny_tribe = mct_mod:add_new_option ("wh_dlc08_nor_goromadny_tribe", "slider")
option_wh_dlc08_nor_goromadny_tribe:set_text("NOR Goromadny Tribe")
option_wh_dlc08_nor_goromadny_tribe:set_tooltip_text("Buff/Debuff for NOR Goromadny Tribe")
option_wh_dlc08_nor_goromadny_tribe:slider_set_min_max(-3, 3)
option_wh_dlc08_nor_goromadny_tribe:slider_set_step_size(1)
option_wh_dlc08_nor_goromadny_tribe:set_default_value(0)

local option_wh_main_nor_graeling = mct_mod:add_new_option ("wh_main_nor_graeling", "slider")
option_wh_main_nor_graeling:set_text("NOR Graeling")
option_wh_main_nor_graeling:set_tooltip_text("Buff/Debuff for NOR Graeling")
option_wh_main_nor_graeling:slider_set_min_max(-3, 3)
option_wh_main_nor_graeling:slider_set_step_size(1)
option_wh_main_nor_graeling:set_default_value(0)

local option_wh_dlc08_nor_helspire_tribe = mct_mod:add_new_option ("wh_dlc08_nor_helspire_tribe", "slider")
option_wh_dlc08_nor_helspire_tribe:set_text("NOR Helspire Tribe")
option_wh_dlc08_nor_helspire_tribe:set_tooltip_text("Buff/Debuff for NOR Helspire Tribe")
option_wh_dlc08_nor_helspire_tribe:slider_set_min_max(-3, 3)
option_wh_dlc08_nor_helspire_tribe:slider_set_step_size(1)
option_wh_dlc08_nor_helspire_tribe:set_default_value(0)

local option_wh2_main_nor_mung = mct_mod:add_new_option ("wh2_main_nor_mung", "slider")
option_wh2_main_nor_mung:set_text("NOR Mung")
option_wh2_main_nor_mung:set_tooltip_text("Buff/Debuff for NOR Mung")
option_wh2_main_nor_mung:slider_set_min_max(-3, 3)
option_wh2_main_nor_mung:slider_set_step_size(1)
option_wh2_main_nor_mung:set_default_value(0)

local option_wh_dlc08_nor_naglfarlings = mct_mod:add_new_option ("wh_dlc08_nor_naglfarlings", "slider")
option_wh_dlc08_nor_naglfarlings:set_text("NOR Naglfarlings")
option_wh_dlc08_nor_naglfarlings:set_tooltip_text("Buff/Debuff for NOR Naglfarlings")
option_wh_dlc08_nor_naglfarlings:slider_set_min_max(-3, 3)
option_wh_dlc08_nor_naglfarlings:slider_set_step_size(1)
option_wh_dlc08_nor_naglfarlings:set_default_value(0)

local option_wh_main_nor_sarl = mct_mod:add_new_option ("wh_main_nor_sarl", "slider")
option_wh_main_nor_sarl:set_text("NOR Sarl")
option_wh_main_nor_sarl:set_tooltip_text("Buff/Debuff for NOR Sarl")
option_wh_main_nor_sarl:slider_set_min_max(-3, 3)
option_wh_main_nor_sarl:slider_set_step_size(1)
option_wh_main_nor_sarl:set_default_value(0)

local option_wh_main_nor_skaeling = mct_mod:add_new_option ("wh_main_nor_skaeling", "slider")
option_wh_main_nor_skaeling:set_text("NOR Skaeling")
option_wh_main_nor_skaeling:set_tooltip_text("Buff/Debuff for NOR Skaeling")
option_wh_main_nor_skaeling:slider_set_min_max(-3, 3)
option_wh_main_nor_skaeling:slider_set_step_size(1)
option_wh_main_nor_skaeling:set_default_value(0)

local option_wh2_main_nor_skeggi = mct_mod:add_new_option ("wh2_main_nor_skeggi", "slider")
option_wh2_main_nor_skeggi:set_text("NOR Skeggi")
option_wh2_main_nor_skeggi:set_tooltip_text("Buff/Debuff for NOR Skeggi")
option_wh2_main_nor_skeggi:slider_set_min_max(-3, 3)
option_wh2_main_nor_skeggi:slider_set_step_size(1)
option_wh2_main_nor_skeggi:set_default_value(0)

local option_wh_dlc08_nor_vanaheimlings = mct_mod:add_new_option ("wh_dlc08_nor_vanaheimlings", "slider")
option_wh_dlc08_nor_vanaheimlings:set_text("NOR Vanaheimlings")
option_wh_dlc08_nor_vanaheimlings:set_tooltip_text("Buff/Debuff for NOR Vanaheimlings")
option_wh_dlc08_nor_vanaheimlings:slider_set_min_max(-3, 3)
option_wh_dlc08_nor_vanaheimlings:slider_set_step_size(1)
option_wh_dlc08_nor_vanaheimlings:set_default_value(0)

local option_wh_main_nor_varg = mct_mod:add_new_option ("wh_main_nor_varg", "slider")
option_wh_main_nor_varg:set_text("NOR Varg")
option_wh_main_nor_varg:set_tooltip_text("Buff/Debuff for NOR Varg")
option_wh_main_nor_varg:slider_set_min_max(-3, 3)
option_wh_main_nor_varg:slider_set_step_size(1)
option_wh_main_nor_varg:set_default_value(0)

local option_wh_dlc08_nor_wintertooth = mct_mod:add_new_option ("wh_dlc08_nor_wintertooth", "slider")
option_wh_dlc08_nor_wintertooth:set_text("NOR Wintertooth")
option_wh_dlc08_nor_wintertooth:set_tooltip_text("Buff/Debuff for NOR Wintertooth")
option_wh_dlc08_nor_wintertooth:slider_set_min_max(-3, 3)
option_wh_dlc08_nor_wintertooth:slider_set_step_size(1)
option_wh_dlc08_nor_wintertooth:set_default_value(0)

local option_wh_dlc08_nor_norsca = mct_mod:add_new_option ("wh_dlc08_nor_norsca", "slider")
option_wh_dlc08_nor_norsca:set_text("NOR World Walkers")
option_wh_dlc08_nor_norsca:set_tooltip_text("Buff/Debuff for NOR World Walkers")
option_wh_dlc08_nor_norsca:slider_set_min_max(-3, 3)
option_wh_dlc08_nor_norsca:slider_set_step_size(1)
option_wh_dlc08_nor_norsca:set_default_value(0)

local option_wh2_main_skv_clan_eshin = mct_mod:add_new_option ("wh2_main_skv_clan_eshin", "slider")
option_wh2_main_skv_clan_eshin:set_text("SKV Clan Eshin")
option_wh2_main_skv_clan_eshin:set_tooltip_text("Buff/Debuff for SKV Clan Eshin")
option_wh2_main_skv_clan_eshin:slider_set_min_max(-3, 3)
option_wh2_main_skv_clan_eshin:slider_set_step_size(1)
option_wh2_main_skv_clan_eshin:set_default_value(0)

local option_wh2_dlc15_skv_clan_ferrik = mct_mod:add_new_option ("wh2_dlc15_skv_clan_ferrik", "slider")
option_wh2_dlc15_skv_clan_ferrik:set_text("SKV Clan Ferrik")
option_wh2_dlc15_skv_clan_ferrik:set_tooltip_text("Buff/Debuff for SKV Clan Ferrik")
option_wh2_dlc15_skv_clan_ferrik:slider_set_min_max(-3, 3)
option_wh2_dlc15_skv_clan_ferrik:slider_set_step_size(1)
option_wh2_dlc15_skv_clan_ferrik:set_default_value(0)

local option_wh2_dlc12_skv_clan_fester = mct_mod:add_new_option ("wh2_dlc12_skv_clan_fester", "slider")
option_wh2_dlc12_skv_clan_fester:set_text("SKV Clan Fester")
option_wh2_dlc12_skv_clan_fester:set_tooltip_text("Buff/Debuff for SKV Clan Fester")
option_wh2_dlc12_skv_clan_fester:slider_set_min_max(-3, 3)
option_wh2_dlc12_skv_clan_fester:slider_set_step_size(1)
option_wh2_dlc12_skv_clan_fester:set_default_value(0)

local option_wh2_main_skv_clan_gnaw = mct_mod:add_new_option ("wh2_main_skv_clan_gnaw", "slider")
option_wh2_main_skv_clan_gnaw:set_text("SKV Clan Gnaw")
option_wh2_main_skv_clan_gnaw:set_tooltip_text("Buff/Debuff for SKV Clan Gnaw")
option_wh2_main_skv_clan_gnaw:slider_set_min_max(-3, 3)
option_wh2_main_skv_clan_gnaw:slider_set_step_size(1)
option_wh2_main_skv_clan_gnaw:set_default_value(0)

local option_wh2_dlc15_skv_clan_kreepus = mct_mod:add_new_option ("wh2_dlc15_skv_clan_kreepus", "slider")
option_wh2_dlc15_skv_clan_kreepus:set_text("SKV Clan Kreepus")
option_wh2_dlc15_skv_clan_kreepus:set_tooltip_text("Buff/Debuff for SKV Clan Kreepus")
option_wh2_dlc15_skv_clan_kreepus:slider_set_min_max(-3, 3)
option_wh2_dlc15_skv_clan_kreepus:slider_set_step_size(1)
option_wh2_dlc15_skv_clan_kreepus:set_default_value(0)

local option_wh2_dlc12_skv_clan_mange = mct_mod:add_new_option ("wh2_dlc12_skv_clan_mange", "slider")
option_wh2_dlc12_skv_clan_mange:set_text("SKV Clan Mange")
option_wh2_dlc12_skv_clan_mange:set_tooltip_text("Buff/Debuff for SKV Clan Mange")
option_wh2_dlc12_skv_clan_mange:slider_set_min_max(-3, 3)
option_wh2_dlc12_skv_clan_mange:slider_set_step_size(1)
option_wh2_dlc12_skv_clan_mange:set_default_value(0)

local option_wh2_main_skv_clan_mordkin = mct_mod:add_new_option ("wh2_main_skv_clan_mordkin", "slider")
option_wh2_main_skv_clan_mordkin:set_text("SKV Clan Mordkin")
option_wh2_main_skv_clan_mordkin:set_tooltip_text("Buff/Debuff for SKV Clan Mordkin")
option_wh2_main_skv_clan_mordkin:slider_set_min_max(-3, 3)
option_wh2_main_skv_clan_mordkin:slider_set_step_size(1)
option_wh2_main_skv_clan_mordkin:set_default_value(0)

local option_wh2_main_skv_clan_mors = mct_mod:add_new_option ("wh2_main_skv_clan_mors", "slider")
option_wh2_main_skv_clan_mors:set_text("SKV Clan Mors")
option_wh2_main_skv_clan_mors:set_tooltip_text("Buff/Debuff for SKV Clan Mors")
option_wh2_main_skv_clan_mors:slider_set_min_max(-3, 3)
option_wh2_main_skv_clan_mors:slider_set_step_size(1)
option_wh2_main_skv_clan_mors:set_default_value(0)

local option_wh2_main_skv_clan_moulder = mct_mod:add_new_option ("wh2_main_skv_clan_moulder", "slider")
option_wh2_main_skv_clan_moulder:set_text("SKV Clan Moulder")
option_wh2_main_skv_clan_moulder:set_tooltip_text("Buff/Debuff for SKV Clan Moulder")
option_wh2_main_skv_clan_moulder:slider_set_min_max(-3, 3)
option_wh2_main_skv_clan_moulder:slider_set_step_size(1)
option_wh2_main_skv_clan_moulder:set_default_value(0)

local option_wh2_main_skv_clan_pestilens = mct_mod:add_new_option ("wh2_main_skv_clan_pestilens", "slider")
option_wh2_main_skv_clan_pestilens:set_text("SKV Clan Pestilens")
option_wh2_main_skv_clan_pestilens:set_tooltip_text("Buff/Debuff for SKV Clan Pestilens")
option_wh2_main_skv_clan_pestilens:slider_set_min_max(-3, 3)
option_wh2_main_skv_clan_pestilens:slider_set_step_size(1)
option_wh2_main_skv_clan_pestilens:set_default_value(0)

local option_wh2_dlc09_skv_clan_rictus = mct_mod:add_new_option ("wh2_dlc09_skv_clan_rictus", "slider")
option_wh2_dlc09_skv_clan_rictus:set_text("SKV Clan Rictus")
option_wh2_dlc09_skv_clan_rictus:set_tooltip_text("Buff/Debuff for SKV Clan Rictus")
option_wh2_dlc09_skv_clan_rictus:slider_set_min_max(-3, 3)
option_wh2_dlc09_skv_clan_rictus:slider_set_step_size(1)
option_wh2_dlc09_skv_clan_rictus:set_default_value(0)

local option_wh2_main_skv_clan_septik = mct_mod:add_new_option ("wh2_main_skv_clan_septik", "slider")
option_wh2_main_skv_clan_septik:set_text("SKV Clan Septik")
option_wh2_main_skv_clan_septik:set_tooltip_text("Buff/Debuff for SKV Clan Septik")
option_wh2_main_skv_clan_septik:slider_set_min_max(-3, 3)
option_wh2_main_skv_clan_septik:slider_set_step_size(1)
option_wh2_main_skv_clan_septik:set_default_value(0)

local option_wh2_main_skv_clan_skyre = mct_mod:add_new_option ("wh2_main_skv_clan_skyre", "slider")
option_wh2_main_skv_clan_skyre:set_text("SKV Clan Skryre")
option_wh2_main_skv_clan_skyre:set_tooltip_text("Buff/Debuff for SKV Clan Skryre")
option_wh2_main_skv_clan_skyre:slider_set_min_max(-3, 3)
option_wh2_main_skv_clan_skyre:slider_set_step_size(1)
option_wh2_main_skv_clan_skyre:set_default_value(0)

local option_wh2_main_skv_clan_spittel = mct_mod:add_new_option ("wh2_main_skv_clan_spittel", "slider")
option_wh2_main_skv_clan_spittel:set_text("SKV Clan Spittel")
option_wh2_main_skv_clan_spittel:set_tooltip_text("Buff/Debuff for SKV Clan Spittel")
option_wh2_main_skv_clan_spittel:slider_set_min_max(-3, 3)
option_wh2_main_skv_clan_spittel:slider_set_step_size(1)
option_wh2_main_skv_clan_spittel:set_default_value(0)

local option_wh2_dlc15_skv_clan_volkn = mct_mod:add_new_option ("wh2_dlc15_skv_clan_volkn", "slider")
option_wh2_dlc15_skv_clan_volkn:set_text("SKV Clan Volkn")
option_wh2_dlc15_skv_clan_volkn:set_tooltip_text("Buff/Debuff for SKV Clan Volkn")
option_wh2_dlc15_skv_clan_volkn:slider_set_min_max(-3, 3)
option_wh2_dlc15_skv_clan_volkn:slider_set_step_size(1)
option_wh2_dlc15_skv_clan_volkn:set_default_value(0)

local option_wh2_main_skv_grey_seer_clan = mct_mod:add_new_option ("wh2_main_skv_grey_seer_clan", "slider")
option_wh2_main_skv_grey_seer_clan:set_text("SKV Grey Seer Clan")
option_wh2_main_skv_grey_seer_clan:set_tooltip_text("Buff/Debuff for SKV Grey Seer Clan")
option_wh2_main_skv_grey_seer_clan:slider_set_min_max(-3, 3)
option_wh2_main_skv_grey_seer_clan:slider_set_step_size(1)
option_wh2_main_skv_grey_seer_clan:set_default_value(0)

local option_wh2_dlc14_skv_rictus_clan_nest = mct_mod:add_new_option ("wh2_dlc14_skv_rictus_clan_nest", "slider")
option_wh2_dlc14_skv_rictus_clan_nest:set_text("SKV Rictus Clan-Nest")
option_wh2_dlc14_skv_rictus_clan_nest:set_tooltip_text("Buff/Debuff for SKV Rictus Clan-Nest")
option_wh2_dlc14_skv_rictus_clan_nest:slider_set_min_max(-3, 3)
option_wh2_dlc14_skv_rictus_clan_nest:slider_set_step_size(1)
option_wh2_dlc14_skv_rictus_clan_nest:set_default_value(0)

local option_wh2_dlc09_tmb_lybaras = mct_mod:add_new_option ("wh2_dlc09_tmb_lybaras", "slider")
option_wh2_dlc09_tmb_lybaras:set_text("TMB Court of Lybaras")
option_wh2_dlc09_tmb_lybaras:set_tooltip_text("Buff/Debuff for TMB Court of Lybaras")
option_wh2_dlc09_tmb_lybaras:slider_set_min_max(-3, 3)
option_wh2_dlc09_tmb_lybaras:slider_set_step_size(1)
option_wh2_dlc09_tmb_lybaras:set_default_value(0)

local option_wh2_dlc09_tmb_dune_kingdoms = mct_mod:add_new_option ("wh2_dlc09_tmb_dune_kingdoms", "slider")
option_wh2_dlc09_tmb_dune_kingdoms:set_text("TMB Dune Kingdoms")
option_wh2_dlc09_tmb_dune_kingdoms:set_tooltip_text("Buff/Debuff for TMB Dune Kingdoms")
option_wh2_dlc09_tmb_dune_kingdoms:slider_set_min_max(-3, 3)
option_wh2_dlc09_tmb_dune_kingdoms:slider_set_step_size(1)
option_wh2_dlc09_tmb_dune_kingdoms:set_default_value(0)

local option_wh2_dlc09_tmb_exiles_of_nehek = mct_mod:add_new_option ("wh2_dlc09_tmb_exiles_of_nehek", "slider")
option_wh2_dlc09_tmb_exiles_of_nehek:set_text("TMB Exiles of Nehek")
option_wh2_dlc09_tmb_exiles_of_nehek:set_tooltip_text("Buff/Debuff for TMB Exiles of Nehek")
option_wh2_dlc09_tmb_exiles_of_nehek:slider_set_min_max(-3, 3)
option_wh2_dlc09_tmb_exiles_of_nehek:slider_set_step_size(1)
option_wh2_dlc09_tmb_exiles_of_nehek:set_default_value(0)

local option_wh2_dlc09_tmb_followers_of_nagash = mct_mod:add_new_option ("wh2_dlc09_tmb_followers_of_nagash", "slider")
option_wh2_dlc09_tmb_followers_of_nagash:set_text("TMB Followers of Nagash")
option_wh2_dlc09_tmb_followers_of_nagash:set_tooltip_text("Buff/Debuff for TMB Followers of Nagash")
option_wh2_dlc09_tmb_followers_of_nagash:slider_set_min_max(-3, 3)
option_wh2_dlc09_tmb_followers_of_nagash:slider_set_step_size(1)
option_wh2_dlc09_tmb_followers_of_nagash:set_default_value(0)

local option_wh2_dlc09_tmb_khemri = mct_mod:add_new_option ("wh2_dlc09_tmb_khemri", "slider")
option_wh2_dlc09_tmb_khemri:set_text("TMB Khemri")
option_wh2_dlc09_tmb_khemri:set_tooltip_text("Buff/Debuff for TMB Khemri")
option_wh2_dlc09_tmb_khemri:slider_set_min_max(-3, 3)
option_wh2_dlc09_tmb_khemri:slider_set_step_size(1)
option_wh2_dlc09_tmb_khemri:set_default_value(0)

local option_wh2_dlc09_tmb_numas = mct_mod:add_new_option ("wh2_dlc09_tmb_numas", "slider")
option_wh2_dlc09_tmb_numas:set_text("TMB Numas")
option_wh2_dlc09_tmb_numas:set_tooltip_text("Buff/Debuff for TMB Numas")
option_wh2_dlc09_tmb_numas:slider_set_min_max(-3, 3)
option_wh2_dlc09_tmb_numas:slider_set_step_size(1)
option_wh2_dlc09_tmb_numas:set_default_value(0)

local option_wh2_dlc09_tmb_rakaph_dynasty = mct_mod:add_new_option ("wh2_dlc09_tmb_rakaph_dynasty", "slider")
option_wh2_dlc09_tmb_rakaph_dynasty:set_text("TMB Rakaph Dynasty")
option_wh2_dlc09_tmb_rakaph_dynasty:set_tooltip_text("Buff/Debuff for TMB Rakaph Dynasty")
option_wh2_dlc09_tmb_rakaph_dynasty:slider_set_min_max(-3, 3)
option_wh2_dlc09_tmb_rakaph_dynasty:slider_set_step_size(1)
option_wh2_dlc09_tmb_rakaph_dynasty:set_default_value(0)

local option_wh2_dlc09_tmb_the_sentinels = mct_mod:add_new_option ("wh2_dlc09_tmb_the_sentinels", "slider")
option_wh2_dlc09_tmb_the_sentinels:set_text("TMB The Sentinels")
option_wh2_dlc09_tmb_the_sentinels:set_tooltip_text("Buff/Debuff for TMB The Sentinels")
option_wh2_dlc09_tmb_the_sentinels:slider_set_min_max(-3, 3)
option_wh2_dlc09_tmb_the_sentinels:slider_set_step_size(1)
option_wh2_dlc09_tmb_the_sentinels:set_default_value(0)

local option_wh_main_vmp_mousillon = mct_mod:add_new_option ("wh_main_vmp_mousillon", "slider")
option_wh_main_vmp_mousillon:set_text("VMP Mousillon")
option_wh_main_vmp_mousillon:set_tooltip_text("Buff/Debuff for VMP Mousillon")
option_wh_main_vmp_mousillon:slider_set_min_max(-3, 3)
option_wh_main_vmp_mousillon:slider_set_step_size(1)
option_wh_main_vmp_mousillon:set_default_value(0)

local option_wh2_main_vmp_necrarch_brotherhood = mct_mod:add_new_option ("wh2_main_vmp_necrarch_brotherhood", "slider")
option_wh2_main_vmp_necrarch_brotherhood:set_text("VMP Necrarch Brotherhood")
option_wh2_main_vmp_necrarch_brotherhood:set_tooltip_text("Buff/Debuff for VMP Necrarch Brotherhood")
option_wh2_main_vmp_necrarch_brotherhood:slider_set_min_max(-3, 3)
option_wh2_main_vmp_necrarch_brotherhood:slider_set_step_size(1)
option_wh2_main_vmp_necrarch_brotherhood:set_default_value(0)

local option_wh2_main_vmp_strygos_empire = mct_mod:add_new_option ("wh2_main_vmp_strygos_empire", "slider")
option_wh2_main_vmp_strygos_empire:set_text("VMP Strygos Empire")
option_wh2_main_vmp_strygos_empire:set_tooltip_text("Buff/Debuff for VMP Strygos Empire")
option_wh2_main_vmp_strygos_empire:slider_set_min_max(-3, 3)
option_wh2_main_vmp_strygos_empire:slider_set_step_size(1)
option_wh2_main_vmp_strygos_empire:set_default_value(0)

local option_wh_main_vmp_vampire_counts = mct_mod:add_new_option ("wh_main_vmp_vampire_counts", "slider")
option_wh_main_vmp_vampire_counts:set_text("VMP Sylvania")
option_wh_main_vmp_vampire_counts:set_tooltip_text("Buff/Debuff for VMP Sylvania")
option_wh_main_vmp_vampire_counts:slider_set_min_max(-3, 3)
option_wh_main_vmp_vampire_counts:slider_set_step_size(1)
option_wh_main_vmp_vampire_counts:set_default_value(0)

local option_wh_main_vmp_rival_sylvanian_vamps = mct_mod:add_new_option ("wh_main_vmp_rival_sylvanian_vamps", "slider")
option_wh_main_vmp_rival_sylvanian_vamps:set_text("VMP Templehof")
option_wh_main_vmp_rival_sylvanian_vamps:set_tooltip_text("Buff/Debuff for VMP Templehof")
option_wh_main_vmp_rival_sylvanian_vamps:slider_set_min_max(-3, 3)
option_wh_main_vmp_rival_sylvanian_vamps:slider_set_step_size(1)
option_wh_main_vmp_rival_sylvanian_vamps:set_default_value(0)

local option_wh2_dlc11_vmp_the_barrow_legion = mct_mod:add_new_option ("wh2_dlc11_vmp_the_barrow_legion", "slider")
option_wh2_dlc11_vmp_the_barrow_legion:set_text("VMP The Barrow Legion")
option_wh2_dlc11_vmp_the_barrow_legion:set_tooltip_text("Buff/Debuff for VMP The Barrow Legion")
option_wh2_dlc11_vmp_the_barrow_legion:slider_set_min_max(-3, 3)
option_wh2_dlc11_vmp_the_barrow_legion:slider_set_step_size(1)
option_wh2_dlc11_vmp_the_barrow_legion:set_default_value(0)

local option_wh2_main_vmp_the_silver_host = mct_mod:add_new_option ("wh2_main_vmp_the_silver_host", "slider")
option_wh2_main_vmp_the_silver_host:set_text("VMP The Silver Host")
option_wh2_main_vmp_the_silver_host:set_tooltip_text("Buff/Debuff for VMP The Silver Host")
option_wh2_main_vmp_the_silver_host:slider_set_min_max(-3, 3)
option_wh2_main_vmp_the_silver_host:slider_set_step_size(1)
option_wh2_main_vmp_the_silver_host:set_default_value(0)

local option_wh_main_vmp_schwartzhafen = mct_mod:add_new_option ("wh_main_vmp_schwartzhafen", "slider")
option_wh_main_vmp_schwartzhafen:set_text("VMP Von Carstein")
option_wh_main_vmp_schwartzhafen:set_tooltip_text("Buff/Debuff for VMP Von Carstein")
option_wh_main_vmp_schwartzhafen:slider_set_min_max(-3, 3)
option_wh_main_vmp_schwartzhafen:slider_set_step_size(1)
option_wh_main_vmp_schwartzhafen:set_default_value(0)

local option_wh_main_vmp_waldenhof = mct_mod:add_new_option ("wh_main_vmp_waldenhof", "slider")
option_wh_main_vmp_waldenhof:set_text("VMP Waldenhof")
option_wh_main_vmp_waldenhof:set_tooltip_text("Buff/Debuff for VMP Waldenhof")
option_wh_main_vmp_waldenhof:slider_set_min_max(-3, 3)
option_wh_main_vmp_waldenhof:slider_set_step_size(1)
option_wh_main_vmp_waldenhof:set_default_value(0)

local option_wh_dlc05_wef_argwylon = mct_mod:add_new_option ("wh_dlc05_wef_argwylon", "slider")
option_wh_dlc05_wef_argwylon:set_text("WEF Argwylon")
option_wh_dlc05_wef_argwylon:set_tooltip_text("Buff/Debuff for WEF Argwylon")
option_wh_dlc05_wef_argwylon:slider_set_min_max(-3, 3)
option_wh_dlc05_wef_argwylon:slider_set_step_size(1)
option_wh_dlc05_wef_argwylon:set_default_value(0)

local option_wh2_main_wef_bowmen_of_oreon = mct_mod:add_new_option ("wh2_main_wef_bowmen_of_oreon", "slider")
option_wh2_main_wef_bowmen_of_oreon:set_text("WEF Bowmen of Oreon")
option_wh2_main_wef_bowmen_of_oreon:set_tooltip_text("Buff/Debuff for WEF Bowmen of Oreon")
option_wh2_main_wef_bowmen_of_oreon:slider_set_min_max(-3, 3)
option_wh2_main_wef_bowmen_of_oreon:slider_set_step_size(1)
option_wh2_main_wef_bowmen_of_oreon:set_default_value(0)

local option_wh2_dlc13_wef_laurelorn_forest = mct_mod:add_new_option ("wh2_dlc13_wef_laurelorn_forest", "slider")
option_wh2_dlc13_wef_laurelorn_forest:set_text("WEF Laurelorn Forest")
option_wh2_dlc13_wef_laurelorn_forest:set_tooltip_text("Buff/Debuff for WEF Laurelorn Forest")
option_wh2_dlc13_wef_laurelorn_forest:slider_set_min_max(-3, 3)
option_wh2_dlc13_wef_laurelorn_forest:slider_set_step_size(1)
option_wh2_dlc13_wef_laurelorn_forest:set_default_value(0)

local option_wh_dlc05_wef_wood_elves = mct_mod:add_new_option ("wh_dlc05_wef_wood_elves", "slider")
option_wh_dlc05_wef_wood_elves:set_text("WEF Talsyn")
option_wh_dlc05_wef_wood_elves:set_tooltip_text("Buff/Debuff for WEF Talsyn")
option_wh_dlc05_wef_wood_elves:slider_set_min_max(-3, 3)
option_wh_dlc05_wef_wood_elves:slider_set_step_size(1)
option_wh_dlc05_wef_wood_elves:set_default_value(0)

local option_wh_dlc05_wef_torgovann = mct_mod:add_new_option ("wh_dlc05_wef_torgovann", "slider")
option_wh_dlc05_wef_torgovann:set_text("WEF Torgovann")
option_wh_dlc05_wef_torgovann:set_tooltip_text("Buff/Debuff for WEF Torgovann")
option_wh_dlc05_wef_torgovann:slider_set_min_max(-3, 3)
option_wh_dlc05_wef_torgovann:slider_set_step_size(1)
option_wh_dlc05_wef_torgovann:set_default_value(0)

local option_wh_dlc05_wef_wydrioth = mct_mod:add_new_option ("wh_dlc05_wef_wydrioth", "slider")
option_wh_dlc05_wef_wydrioth:set_text("WEF Wydrioth")
option_wh_dlc05_wef_wydrioth:set_tooltip_text("Buff/Debuff for WEF Wydrioth")
option_wh_dlc05_wef_wydrioth:slider_set_min_max(-3, 3)
option_wh_dlc05_wef_wydrioth:slider_set_step_size(1)
option_wh_dlc05_wef_wydrioth:set_default_value(0)


